# For Federated Learning
comm_round : 200
client_sample : 0.1
client_number : 100
thread_number : 10
partition_method: "hetero"
partition_alpha: 0.1

# For Local Training
dataset: "cifar10"
datadir: "/cpfs/user/haotan2/FL/Mutil-FL-Training-main/dataset/cifar10"
batch_size: 64
lr : 0.01
wd : 0.0001
epochs: 10
local_valid: False
DEVICE : "cuda:0"
